#spring:
#  application:
#    name: eureka-server
spring:
  config:
    import: optional:configserver:http://localhost:8880/
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false

